#!/bin/sh

OLDPATH=$PATH; PATH=".:..:$(dirname $0):$PATH"; . _spmon_lib; PATH=$OLDPATH

COOKIE_FILE=$LOGIN

# Input: LOGIN, PASSWORD
# Output: account balance

request -O $TM/1.html 'https://ip.mts.ru/SELFCAREPDA/Home.mvc'

if grep -q -m 1 Пароль $TM/1.html 
then
	request -O $TM/1.html --post-data="username=$LOGIN&password=$PASSWORD" 'https://ip.mts.ru/SELFCAREPDA/Security.mvc/LogOn?returnLink=http%3A%2F%2Fihelper.mts.ru%3A8083%2FSELFCAREPDA%2FHome.mvc'
fi


#                         <br/>Баланс: <strong><strong>123.45</strong> руб.</strong>

sed -ne '/<br\/>Баланс:/ { s,.*>\([0-9.]*\)</.*$,\1,; p }' < $TM/1.html | sed -e 's/,/./' | sed 's/^[^0-9]*\([0-9]*\.[0-9]*\).*$/\1/'

